### ISSUE TITLE
Missing openCV

### ISSUE THREAD

**Issue by matjaz** [CircuitMess/Arduino-Packages#1]
[100%] Generating ../build/Wheelson-Firmware.ino.elf
In file included from Wheelson-Firmware/src/Apps/Autonomous/BallDriver.h:6:0,
                 from Wheelson-Firmware/src/Apps/Autonomous/BallDriver.cpp:1:
~/Library/Arduino15/packages/cm/hardware/esp32/1.2.1/libraries/Wheelson-Library/src/BallTracker.h:5:23: fatal error: opencv2.hpp: No such file or directory

Please update Arduino-Packages

**Comment by filipbudisa** [comment]
Hello,

I've updated the package with the missing libraries. You can update through the Arduino board manager or by starting CircuitBlocks which will do that automatically. I apologize for the inconvenience.

Filip
