### ISSUE TITLE
Missing board definitions for armstrong

### ISSUE THREAD

**Issue by Susko3** [CircuitMess/Arduino-Packages#3]
I'm trying to build and modify the [armstrong firmware](https://github.com/CircuitMess/Armstrong-Firmware), but it seems the board name in question (`cm:esp32:armstrong`) isn't available in this index:

```pwsh
❯ arduino-cli core update-index
Downloading index: package_index.tar.bz2 downloaded
Downloading index: package_circuitmess.com_esp32_index.json downloaded
❯ arduino-cli board listall    
Board Name                FQBN                
ByteBoi by CircuitMess    cm:esp32:byteboi
Chatter by CircuitMess    cm:esp32:chatter
CircuitPet by CircuitMess cm:esp32:circuitpet
Jay-D by CircuitMess      cm:esp32:jayd
Ringo by CircuitMess      cm:esp32:ringo
Spencer by CircuitMess    cm:esp32:spencer
Synthia by CircuitMess    cm:esp32:synthia
Wheelson by CircuitMess   cm:esp32:wheelson
```

**Comment by Susko3** [comment]
bump

CC @filipbudisa since you contributed to this repository

**Comment by filipbudisa** [comment]
Hello!

Apologies for the long wait. We've updated the platform yesterday with the missing devices. Armstrong is added now and you should be able to build the firmware after pulling the new platform update.

Feel free to reopen this issue if any problems remain.

Filip
